name: Social
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  bluesky:
    runs-on: ubuntu-latest
    steps:
      - name: Post 🌤️
        id: bluesky
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410
        with:
          script: |
            const { BskyAgent } = require("@atproto/api");

            let release = context.payload.release;

            if (!release) {
                release = github.repos.getLatestRelease({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                });
            }

            let notes = release.body;

            // replace all non-supported characters
            notes = notes.replaceAll('###', '');
            notes = notes.replaceAll('**', '');
            notes = notes.replace(/ \(\[[0-9a-z]+\]\(.*\)/g, '');
            notes = notes.trim();

            const agent = new BskyAgent({ service: 'https://bsky.social' });
            await agent.login({identifier: '${{ secrets.BLUESKY_IDENTIFIER }}', password: '${{ secrets.BLUESKY_PASSWORD }}'});

            const version = release.name;

            const text = `📦 ${version}

            ${notes}

            #ohmyposh #oss #cli #opensource`;

            await agent.post({
                text: text,
                embed: {
                    $type: 'app.bsky.embed.external',
                    external: {
                        uri: `https://github.com/JanDeDobbeleer/oh-my-posh/releases/tag/${version}`,
                        title: "The best release yet 🚀",
                        description: version,
                    },
                },
            });
